### ISSUE TITLE
Getting error: Schema.kind_to_string: object without additional_properties

### ISSUE THREAD

**Issue by carlosdagos** [andrenth/ocaml-swagger#11]
Hello!

I'm trying to use this lib with [this schema](https://api.youneedabudget.com/papi/spec-v1-swagger.json) and I'm getting the error:

```ocaml
Swagger.codegen
  ~input:"/path/to/spec-v1-swagger.json"
  ~output:stdout
  ~path_base:"/"
  ~definition_base:"/"
  ~reference_base:""
  ~reference_root:"definitions"
;;
```

And I'm getting the following

```
Exception:
Failure "Schema.kind_to_string: object without additional_properties".
```

(It's very likely I'm getting the invocation wrong.)

Thanks!

**Comment by rdavison** [comment]
I'm not completely sure about the invocation that you're using (nothing stands out as obviously wrong about it).  However, it looks like the schema doesn't define any `additionalProperties` fields.  As far as I know, the field is optional within the swagger spec, but `ocaml-swagger` doesn't handle the case when it is not present.  You can see that here: https://github.com/andrenth/ocaml-swagger/blob/master/src/schema.ml#L39

I'm not really sure what would be the correct way of handling it, seeing as OCaml requires the type to be known ahead of time.

**Comment by rdavison** [comment]
So, I looked a little further into it, it looks like the types *are* being specified, but a level above.  I would say someone would have to tinker with the code generator in order to correctly output the necessary types.

**Comment by carlosdagos** [comment]
> it looks like the types are being specified, but a level above

I noticed this when comparing to, say, the Kubernetes one. Looks like `ocaml-swagger` is making an assumption about the structure.

Thanks for replying to my issue @rdavison 👍

**Comment by carlosdagos** [comment]
Took a closer look and figured out that `ocaml-swagger` was just misinterpreting the semantics of `additionalProperties`. I think I've got a fix for it. Will submit a PR and see what you and the library author think :)
