### ISSUE TITLE
Support for "default" responses

### ISSUE THREAD

**Issue by carlosdagos** [andrenth/ocaml-swagger#13]
I get the error `Exception: Failure "int_of_string".` when there's a response with "default".

The documentation for that is here: https://swagger.io/docs/specification/describing-responses/#default

Thanks!

**Comment by andrenth** [comment]
Merged your PR, thanks! Sorry for the really slow handling of issues and PRs.

**Comment by carlosdagos** [comment]
Thanks a lot @andrenth :tada:
